name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ayush-govindwar
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit generated snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "output/"
